#!/bin/sh
set -eux

install -d -m 755 -o root -g root /var/lib/ldap-account-manager
cp --archive --no-clobber --verbose --no-target-directory /var/lib/ldap-account-manager.orig /var/lib/ldap-account-manager
eval exec "$@"
