#!/usr/bin/env php
<?php

include_once('/usr/share/ldap-account-manager/lib/config.inc');

// For the general settings.
$cfg = new LAMCfgMain();
$cfg->setPassword($argv[1]);
$cfg->save();

// For the server profiles.
$profile_manager = new ServerProfilePersistenceManager();
$conf = $profile_manager->loadProfile("lam");
$conf->set_Passwd($argv[1]);
$profile_manager->saveProfile($conf, "lam");
