#!/bin/sh
set -eux

alias slapcat='slapcat -vF /var/lib/ldap/config'

slapcat -n0 -l /var/backups/ldap/config.ldif

for dn in $(ldapsearch -Y EXTERNAL -LLL -s base -b '' o namingContexts | sed -n '/namingContexts/ s/namingContexts: //gp')
do
    slapcat -b "$dn" -l "/var/backups/ldap/$dn.ldif"
done
