#!/bin/sh
set -eux

chown -R openldap:openldap /run/slapd
chown -R openldap:openldap /var/lib/ldap

cat << EOF | debconf-set-selections -v
slapd slapd/internal/generated_adminpw password ${LDAP_ROOTPASS:-}
slapd slapd/internal/adminpw password ${LDAP_ROOTPASS:-}
slapd slapd/password2 password ${LDAP_ROOTPASS:-}
slapd slapd/password1 password ${LDAP_ROOTPASS:-}
slapd slapd/domain string ${LDAP_DOMAIN:-}
slapd shared/organization string ${LDAP_ORGANIZATION:-}
EOF

dpkg-reconfigure -f noninteractive slapd

eval exec "$@"
